theme: jekyll-theme-minimal
title: NBestsuNgan
description: Data Engineering · Software Development · DevOps
show_downloads: true
google_analytics:
logo: https://github.com/NBestsuNgan.png
author:
  name: NBestsuNgan
  github: NBestsuNgan
  url: https://github.com/NBestsuNgan
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
defaults:
  - scope:
      path: ""
    values:
      image: https://github.com/NBestsuNgan.png
